feat/add-login-feature
tolehoai/carForRent pull request #3
Opened 2022-05-20 01:58 UTC by tolehoai

2022-05-24 10:16 UTC, bangdinhnfq requested changes

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Boostrap/Container.php
> +//            $dependency = $parameter->getClass();
Remove comment code

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Boostrap/Container.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Boostrap/Response.php
> +use http\Client\Curl\User;
Wrong import

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Controller/UserController.php
> +                $errorMessage = 'The username or password is invalid!';
Should defined as a constant and centralized it.

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Controller/UserController.php
> +    public
Should not format like this

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Model/Session.php
> +    public $id;
Should not public variable

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Model/Session.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Model/User.php
> +    public $id;
Should not public variable

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Repository/SessionRepository.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Route/route.php
> +//$userRepository = new UserRepository();
Remove unused code

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Service/DatabaseService.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Service/SessionService.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Transfer/UserTransfer.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on src/Validator/UserValidator.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on tests/Tolehoai/CarForRent/UserTransfer/UserTransferTest.php
> +}
EOL

2022-05-24 10:16 UTC, bangdinhnfq commented on tests/Tolehoai/CarForRent/Validator/UserValidatorTest.php
> +}
EOL

2022-05-28 03:41 UTC, bangdinhnfq commented on src/Controller/SiteController.php
> +}
EOL

2022-05-28 03:41 UTC, bangdinhnfq commented on src/Controller/UserApiController.php
> +}
EOL

2022-05-28 03:42 UTC, bangdinhnfq commented on src/Controller/UserApiController.php
> +            return $this->response->setResponseDataSuccess([...$userTransformer,'AccessToken'=>$accessToken]);
Need to change from `AccessToken` => to `token`

2022-05-28 03:43 UTC, bangdinhnfq commented on src/Service/UserService.php
> +            $userTransformer = $this->userTransformer->transform($existUser);
If login success should return a User, not a UserTransformer

2022-06-06 14:47 UTC, khajackie2206 commented on src/Repository/UserRepository.php
>              return ["error" => "Error when query"];
error must be in plural (errors)

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Controller/LoginControllerTest.php
> +}
EOL

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Model/CarTest.php
> +}
EOL

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Service/RegisterServiceTest.php
> +}
EOL

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Transfer/CarTransferTest.php
> +}
EOL

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Transfer/CarTransferTest.php
> +
an empty line?

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Transfer/CarTransferTest.php
> +
Empty line is also here :)))

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Transfer/RegisterTransferTest.php
> +}
EOL

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Transformer/CarTransformerTest.php
> +}
EOL

2022-06-06 14:47 UTC, khajackie2206 commented on tests/Tolehoai/CarForRent/Validator/RegisterValidatorTest.php
> +}
EOL

2022-06-07 02:32 UTC, merged